### ISSUE TITLE
Compiling with the build.sh

### ISSUE THREAD

**Issue by RuneHeick** [edgeimpulse/example-standalone-inferencing-c#1]
When building I get the issue: 

```
undefined reference to `(anonymous namespace)::can_run_classifier_image_quantized()'
```

Since this is omitted by the precompiler flag: EIDSP_SIGNAL_C_FN_POINTER=1

**Comment by automatiek** [comment]
Hi RuneHeick, thanks for your input. 

We've updated the SDK to resolve this issue.
